src/Entity/Band.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\String\Slugger\AsciiSlugger;

/**
 * Band
 *
 * @ORM\Table(name="band")
 * @ORM\Entity(repositoryClass="App\Repository\BandRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Band {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private string $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private string $description;

    /**
     * @var string
     *
     * @ORM\Column(name="logo", type="string", length=255, nullable=true)
     */
    private ?string $logo;

    /**
     * @var string
     *
     * @ORM\Column(name="banner",  type="string", length=255, nullable=true)
     */
    private ?string $banner = null;

    /**
     * @ORM\ManyToMany(targetEntity="User", inversedBy="bands")
     */
    private mixed $members;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="managedBands")
     */
    private mixed $manager;

    /**
     * @ORM\OneToMany(targetEntity="Project", mappedBy="band")
     */
    private $projects;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="createdBands")
     */
    private mixed $created_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $updated_at;

    public function __construct(UserInterface $created_by) {
        $this->members = new ArrayCollection();
        $this->created_by = $created_by;
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(string $name): self {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string {
        return $this->slug;
    }

    public function setSlug(string $slug): self {
        $slugger = new AsciiSlugger();
        $this->slug = $slugger->slug(strtolower($slug));

        return $this;
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    public function setDescription(string $description): self {
        $this->description = $description;

        return $this;
    }

    public function getLogo(): ?string {
        return $this->logo ?? null;
    }

    public function setLogo(?string $logo): self {
        // Only update the logo property if a non-null value is provided
        if ($logo !== null) {
            $this->logo = $logo;
        }
        return $this;
    }

    public function removeLogo(): self {
        $this->logo = null;

        return $this;
    }

    public function getBanner(): ?string {
        return $this->banner ?? null;
    }

    public function setBanner(?string $banner): self {
        if ($banner !== null) {
            $this->banner = $banner;
        }
        return $this;
    }
    public function removeBanner(): self {
        $this->banner = null;

        return $this;
    }

    /**
     * Get the value of Members
     *
     * @return mixed
     */
    public function getMembers(): mixed {
        return $this->members;
    }

    /**
     * Set the value of Members
     *
     * @param mixed $members members
     *
     * @return Band
     */
    public function setMembers(mixed $members): static {
        $this->members = $members;

        return $this;
    }

    /**
     * Set the value of Members
     *
     * @param $member
     *
     * @return Band
     */
    public function addMember($member): Band {
        $this->members[] = $member;
        $member->setBand($this);

        return $this;
    }

    /**
     * Set the value of Members
     *
     * @param $member
     *
     * @return Band
     */
    public function removeMember($member): Band {
        $this->members->removeElement($member);

        return $this;
    }

    /**
     * Get the value of Manager
     *
     * @return mixed
     */
    public function getManager()
    {
        return $this->manager;
    }

    /**
     * Set the value of Manager
     *
     * @param mixed manager
     *
     * @return Band
     */
    public function setManager($manager)
    {
        $this->manager = $manager;

        return $this;
    }


    /**
     * Get the value of projects
     *
     * @return mixed
     */
    public function getProjects()
    {
        return $this->projects;
    }

    /**
     * Set the value of projects
     *
     * @param mixed projects
     *
     * @return User
     */
    public function setProjects($projects)
    {
        $this->projects = $projects;

        return $this;
    }

    /**
     * Get the value of createdBy
     *
     * @return UserInterface
     */
    public function getCreatedBy(): UserInterface
    {
        return $this->created_by;
    }

    public function getCreatedAt(): ?DateTimeInterface {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface {
        return $this->updated_at;
    }

    public function setUpdatedAt(?DateTimeInterface $updated_at): self {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/BandType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class BandType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null,
                [
                    'label' => 'Nom',
                ]
            )
            ->add('description', TextareaType::class,
                [
                    'label' => 'Description',
                    'attr' => ['class' => 'tinymce']
                ]
            )
            ->add('logo', FileType::class, [
                    'label' => 'Logo',
                    'data_class' => null,
                    'required' => false
                ]
            )
            ->add('banner', FileType::class, [
                    'label' => 'Bannière',
                    'data_class' => null,
                    'required' => false
                ]
            )
        ;

        if ($options['is_update_form']) {
            $builder
                ->add('remove_logo', CheckboxType::class, [
                    'required' => false,
                    'mapped' => false, // Do not map this field to the entity
                ])
                ->add('remove_banner', CheckboxType::class, [
                    'required' => false,
                    'mapped' => false, // Do not map this field to the entity
                ]);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Band',
            'attr' => array('novalidate' => 'novalidate'),
            'is_update_form' => false
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_band';
    }


}

src/Controller/Admin/BandController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Band;
use App\Form\BandType;
use App\Service\FileUploader;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

;

/**
 * @Route("/admin/band", name="admin_band_")
 * @IsGranted("ROLE_ADMIN")
 */
class BandController extends AdminBaseController {
    /**
     * @Route("/", name="list", methods={"GET"})
     * @param Request $request
     * @return Response
     */
    public function list(): Response {
        return parent::list();
    }

    /**
     * @Route("/{slug}/edit", name="update", methods={"GET", "POST"})
     * @param string $slug
     * @param Request $request
     * @param FileUploader $fileUploader
     * @return Response
     * @throws \Exception
     */
    public function update(string $slug, Request $request, FileUploader $fileUploader): Response {
        $em = $this->doctrine->getManager();

        $bandRepo = $em->getRepository(Band::class);
        $band = $bandRepo->findOneBySlug($slug);
        $oldLogo = $band->getLogo();
        $oldBanner = $band->getBanner();
        if(!$band instanceof Band) {
            return new Response(null, 404);
        }

        $form = $this->createForm(BandType::class, $band, [
            'is_update_form' => true,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Check if the "remove logo" checkbox is checked
            $removeLogo = $form->get('remove_logo')->getData();
            if ($removeLogo) {
                // Remove the logo and set the logo property to null
                $logoFolder = $fileUploader->getTargetDirectory('band_logo');
                if ($oldLogo !== null) {
                    unlink("$logoFolder/$oldLogo");
                }
                $band->removeLogo();
            } else {
                // Check if a new logo file was uploaded
                $logoFile = $form['logo']->getData();
                if ($logoFile) {
                    // Upload the new logo file and set the logo property
                    $logoFilename = $fileUploader->upload($logoFile, 'band_logo');
                    $band->setLogo($logoFilename);

                    // Remove the old logo file
                    $logoFolder = $fileUploader->getTargetDirectory('band_logo');
                    if ($oldLogo !== null) {
                        unlink("$logoFolder/$oldLogo");
                    }
                }
            }
            $removeBanner = $form->get('remove_banner')->getData();
            if ($removeBanner) {
                // Remove the banenr and set the logo property to null
                $bannerFolder = $fileUploader->getTargetDirectory('band_banner');
                if ($oldBanner !== null) {
                    unlink("$bannerFolder/$oldBanner");
                }
                $band->removeBanner();
            } else {
                // Check if a new banner file was uploaded
                $bannerFile = $form['banner']->getData();
                if ($bannerFile) {
                    // Upload the new banner file and set the banner property
                    $bannerFilename = $fileUploader->upload($bannerFile, 'band_banner');
                    $band->setBanner($bannerFilename);

                    // Remove the old banner file
                    $bannerFolder = $fileUploader->getTargetDirectory('band_banner');
                    if ($oldBanner !== null) {
                        unlink("$bannerFolder/$oldBanner");
                    }
                }
            }

            $currentDate = new \Datetime();
            $band = $form->getData();
            $band->setSlug($band->getName());
            $band->setUpdatedAt($currentDate);
            $em->persist($band);
            $em->flush();

            $this->adminHistoryService->addHistory($this->getUser(), 'update', 'band', $band->getId(), $band->getName());

            return $this->redirectToRoute('admin_band_list', [
                'slug' => $band->getSlug()
            ]);
        }

        return $this->render('admin/band/update.html.twig', [
            'band' => $band,
            'form' => $form->createView()
        ]);
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Band;
use App\Entity\News;
use App\Entity\Project;
use Doctrine\Persistence\ObjectManager;
use Psr\Container\ContainerExceptionInterface;
use Psr\Container\NotFoundExceptionInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends BaseController {
    /**
     * @Route("/", name="homepage")
     * @return Response
     * @throws ContainerExceptionInterface
     * @throws NotFoundExceptionInterface
     */
    public function homepage(): Response {
        $random = [];
        /** @var ObjectManager $em */
        $em = $this->doctrine->getManager();

        $newsRepo = $em->getRepository(News::class);
        $news = $newsRepo->findBy([], ['created_at' => 'DESC']);

//        foreach ($news as $newsItem) {
//            $newsItem->setMessage(nl2br($newsItem->getMessage()));
//        }

        $projectRepo = $em->getRepository(Project::class);
        $random['project'] = $projectRepo->getRandom(15);
        $bandRepo = $em->getRepository(Band::class);
        $random['band'] = $bandRepo->getRandom(15);

        return $this->render('homepage.html.twig', [
            'news' => $news,
            'random' => $random
        ]);
    }
}

templates/default/band/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'new_band'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
    <a href="{{ path('homepage') }}">{{ 'home'|trans|capitalize }}</a> &gt;
    <span class="bc-current">{{ 'new_band'|trans|capitalize }}</span>
{% endblock %}

{% block body %}
    <h1>{{ 'new_band'|trans|capitalize }}</h1>
    <small class="text-secondary">{{ 'required_fields'|trans|capitalize }}</small>
    {{ form_start(form, {'attr': {'id': 'band-form'}}) }}
    {{ form_widget(form) }}
    <input type="submit" value="{{ 'create'|trans|capitalize }}" class="btn btn-secondary"/>
    {{ form_end(form) }}

    <ul>
        <li>
            <a href="{{ path('homepage') }}">
                <button class="btn btn-secondary" type="button" name="button">Retour</button>
            </a>
        </li>
    </ul>
{% endblock %}

templates/default/band/detail.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('band') }}
{% endblock %}
{% block title %}{{ band.name }}{% endblock %}

{% block breadcrumb %}
    <a href="{{ path('homepage') }}">{{ 'home'|trans|capitalize }}</a> &gt;
    <a href="{{ path('band_list') }}">{{ 'bands'|trans|capitalize }}</a> &gt;
    <span class="bc-current">{{ band.name }}</span>
{% endblock %}

{% block body %}

    {% if  band.banner %}
        <img class="band-banner" src="{{ asset('media/band/banner/' ~ band.banner) }}" alt="band banner">
    {% endif %}
    <h1 class="band-name">{{ band.name }}</h1>

    <hr class="w-66 m-2">

    <div class="band-infos row">
        <div class="col-2">
            <img class="band-logo" src="{{ asset('media/band/logo/' ~ band.logo|default('default.png')) }}" alt="band logo">
        </div>
        <div class="band-description col-8">{{ band.description|raw }}</div>
        <div  class="col-2">
            {% if app.user == band.manager %}
                <a href="{{ path('band_update', {slug: band.slug}) }}" class="update-band-button btn btn-warning">
                    {{ 'update_informations'|trans|capitalize }}
                </a>
            {% endif %}
        </div>
{#        <div class="band-meta">#}
{#            Fondé le {{ band.createdAt|date('d M Y') }} par#}
{#            <a href="{{ path('user_detail', { 'slug': band.createdBy.slug }) }}">{{ band.createdBy.username }}</a>#}
{#        </div>#}
    </div>

    <hr class="w-66 m-2">

    <div>

    </div>
    <h2>{{ 'members'|trans|capitalize }}</h2>
    <ul>
        {% if band.createdBy not in band.members %}
            <li>
                <a href="{{ path('user_detail', { 'slug': band.createdBy.slug }) }}"
                   class="former-member">{{ band.createdBy.username }}</a>
                <span  class="btn btn-badge btn-primary">Fondateur</span>
            </li>
        {% endif %}

        {% for member in band.members %}
            <li>
                <a href="{{ path('user_detail', { 'slug': member.slug }) }}">{{ member.username }}</a>
                {% if member == band.manager %}
                    <span class="btn btn-badge btn-warning">Manager</span>
                {% endif %}
                {% if member == band.createdBy %}
                    <span  class="btn btn-badge btn-primary">Fondateur</span>
                {% endif %}

            </li>
        {% endfor %}
    </ul>
    {% if app.user in band.members%}
        {% if app.user == band.manager %}
            <a href="{{ path('band_update_manager', {slug: band.slug}) }}" class="btn btn-warning">{{ 'change_manager'|trans|capitalize }}</a>
            <a href="{{ path('band_handle_members', {slug: band.slug}) }}" class="btn btn-warning">{{ 'handle_members'|trans|capitalize }}</a>
        {% endif %}
        {% if (band.members | length > 1) %}
            <button class="btn btn-danger" id="leave-band-btn">Leave the band</button>
        {% endif %}
    {% else %}
        <a href="{{ path('band_join_request', { 'slug': band.slug }) }}"><button class="btn btn-primary" id="join-band-btn">Join the
                band</button></a>
    {% endif %}

    <!-- Confirmation modal -->
    <div class="modal fade" id="confirm-leave-band-modal" tabindex="-1" role="dialog" aria-labelledby="confirm-leave-band-modal-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirm-leave-band-modal-label">Leave band confirmation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to leave the band?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <a href="{{ path('band_leave', {'slug': band.slug}) }}" id="confirm-leave-band-link"><button class="btn btn-danger">Leave the band</button></a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/default/band/handle_members.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'handle_members'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
  <a href="{{ path('homepage') }}">{{ 'home'|trans|capitalize }}</a> &gt;
  <a href="{{ path('band_list') }}">{{ 'bands'|trans|capitalize }}</a> &gt;
  <a href="{{ path('band_detail', { 'slug': band.slug }) }}">{{ band.name }}</a> &gt;
  <span class="bc-current">{{ 'handle_members'|trans|capitalize }}</span>
{% endblock %}

{% block body %}

{% endblock %}

templates/default/band/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'band'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
    <a href="{{ path('homepage') }}">{{ 'home'|trans|capitalize }}</a> &gt;
    <span class="bc-current">{{ 'bands'|trans|capitalize }}</span>
{% endblock %}

{% block body %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        {% include 'parts/search_form.html.twig' with { type: 'band', key: ['name', 'slug'] } %}
        <a href="{{ path('band_create') }}" class="btn btn-secondary">{{ 'create'|trans|capitalize }}</a>
        {% if bandList %}
            <table>
                <thead>
                    <th>{{ 'name'|trans|capitalize }}</th>
                </thead>
                <tbody>
                {% for band in bandList %}
                    <tr>
                        <td><a href="{{ path('band_detail', { 'slug': band.slug }) }}">{{ band.name }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>{{ 'nothing_to_display'|trans|capitalize }}</p>
        {% endif %}
    {% endif %}
{% endblock %}

templates/default/band/search.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <ul>
  {% for result in results %}
    <li><a href="{{ path('band_detail', {'slug': result.slug}) }}">{{ result.name }}</a></li>
  {% endfor %}
  </ul>
  <div class="col-md-12">
    {% if results is empty %}
      <p class="h3">{{ 'no_results'|trans }}</p>
    {% endif %}
  </div>
{% endblock %}

templates/default/band/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ band.name }}{% endblock %}

{% block breadcrumb %}
  <a href="{{ path('homepage') }}">{{ 'home'|trans|capitalize }}</a> &gt;
  <a href="{{ path('band_list') }}">{{ 'bands'|trans|capitalize }}</a> &gt;
  <a href="{{ path('band_detail', { 'slug': band.slug }) }}">{{ band.name }}</a> &gt;
  <span class="bc-current">{{ 'edit'|trans|capitalize }}</span>
{% endblock %}

{% block body %}
  {{ form_start(form) }}
  {{ form_row(form.name) }}
  {{ form_row(form.description) }}
  {{ form_row(form.logo) }}
  {% if band.logo %}
    {{ form_row(form.remove_logo, {
      label: '<span class="iconify" data-icon="dashicons:trash" data-inline="false"></span> Remove logo',
      label_html: true
    }) }}
  {% else %}
    {{ form_row(form.remove_logo, {
      attr: {'style': 'display:none'},
      label_attr: {'style': 'display:none'}
    }) }}
  {% endif %}

  {{ form_row(form.banner) }}
  {% if  band.banner %}
    {{ form_row(form.remove_banner, {
      label: '<span class="iconify" data-icon="dashicons:trash" data-inline="false"></span> Remove banner',
      label_html: true
    }) }}
  {% else %}
    {{ form_row(form.remove_banner, {
      attr: {'style': 'display:none'},
      label_attr: {'style': 'display:none'}
    }) }}
  {% endif %}
  <input class="button btn btn-secondary" type="submit" value="{{ 'validate'|trans|capitalize }}"/>
  <button type="button" name="button" class="btn btn-secondary">
    <a href="{{ path('band_detail', { 'slug': band.slug }) }}">{{ 'back'|trans|capitalize }}</a>
  </button>
  {{ form_end(form) }}

{% endblock %}

templates/default/band/update_manager.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'change_manager'|trans|capitalize }}{% endblock %}

{% block breadcrumb %}
  <a href="{{ path('homepage') }}">{{ 'home'|trans|capitalize }}</a> &gt;
  <a href="{{ path('band_list') }}">{{ 'bands'|trans|capitalize }}</a> &gt;
  <a href="{{ path('band_detail', { 'slug': band.slug }) }}">{{ band.name }}</a> &gt;
  <span class="bc-current">{{ 'change_manager'|trans|capitalize }}</span>
{% endblock %}

{% block body %}
  <h1>{{ 'change_manager'|trans|capitalize }}</h1>
  {{ form_start(form, {'attr': {'id': 'band-form', 'action': path('band_update_manager', {'slug': band.slug}) }}) }}
  {{ form_widget(form) }}
  <button type="submit" class="btn btn-secondary" id="update-manager-btn">{{ 'validate'|trans|capitalize }}</button>
  {{ form_end(form) }}

  <ul>
    <li>
      <a href="{{ path('homepage') }}">
        <button class="btn btn-secondary" type="button" name="button">Retour</button>
      </a>
    </li>
  </ul>

  <!-- Confirmation modal -->
  <div class="modal fade" id="confirm-update-manager-modal" tabindex="-1" role="dialog" aria-labelledby="confirm-update-manager-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="confirm-update-manager-modal-label">Update manager confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          After this, you will not be manager of this band anymore. All associated privileges associated to this role will be anavailable for you.
          Are you sure you want to update the band manager?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger" id="confirm-update-manager-btn">I'm sure</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}